Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/MethodLength:
  Max: 15
