Documentation:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/Encoding:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'bin/console'
    - 'exe/rucompd'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'bin/console'
    - 'exe/rucompd'

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 26

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 8
